### ISSUE TITLE
Read/write flash status registers

### ISSUE THREAD

**Issue by DurandA** [gregdavill/ecpprog#1]
Hi @gregdavill and sorry for taking up so much of your time.

I'd like to extend _ecpprog_ to read/write flash status registers since the _ecp5_evn_ board has a chip ([_Macronix MX25L12833F_](https://www.macronix.com/Lists/Datasheet/Attachments/7447/MX25L12833F,%203V,%20128Mb,%20v1.0.pdf)) that have QIO disabled by default and I am unsure about how dummy cycles are configured.
- Would you accept such a PR?
- Do you have an idea of a clean API for that? I think the registers name are inconsistent between vendors (i.e. QE is bit 2 of FC_RSR2 (0x35) for _Winbond W25Q128JV_ while it is bit 6 of FC_RSR3 (0x05) for _MX25L12833F_) so maybe it is better to use opcodes directly.

Also do you know how the ECP5 handles the various flash configurations (e.g. dummy cycles, DIO/QIO) for transparent JTAG programming and for loading bitstream from flash? Does the ECP5 expect a flash chip always in a specific configuration?

Many thanks!

**Comment by gregdavill** [comment]
The main issue I see, which you've identified is that there are lots of different FLASH chips available. And while most stick to industry defined registers, there are lots of exceptions.

I think initially maybe we can support some form of raw mode. Which will basically give you peek/poke access to these registers. But you need to know the register addresses yourself.

The ECP5 shouldn't care about dummy cycles, it always starts with a standard read. It will read a few hundred bytes looking for the start of a bit-stream, once it has this is starts loading. 

One of the early frames contains configuration for the sysconfig, which enables QSPI and faster clock rates. 

To be honest, I'm not entirely sure what happens at that point if QSPI is enabled, maybe it restarts loading from 0x0 but in QSPI mode? Or it restarts from the current frame, but in QSPI mode.

**Comment by DurandA** [comment]
I have to postpone this until I can get my hands on some fast-enough logic analyser.

My flash chip doesn't respond to some commands as it should per the datasheet so I have to fallback to using an external MCU.

**Comment by gregdavill** [comment]
Interesting. There are a few things that you need to make sure of before you can communicate with the SPI bus.

1. ECP5 can not be configured to use the SPI interface. (We perform a bitstream reset to ensure this)
2. You need to run `enter_spi_background_mode()`
3. The CS line is active when in the SHIFT-DR state, CLK, TDI/TDO are connected directly to teh SPI bus.

When poking around with new stuff it's easiest to add it here to test: https://github.com/gregdavill/ecpprog/blob/master/ecpprog/ecpprog.c#L955 
That way the SPI bus is already configured, and you can verify the SPI_ID is correct before your custom functions run.

Note when writing data to the Status registers calling `flash_write_enable()` is required as the instruction right before the write. `flash_disable_protection()` is an example of performing this write and validating the result.

The SPI I/O drivers on the ECP5 are very fast, you may need to place an inline resistor with CLK. I've found that when my logic analyser was attached, there was extra ringing on the CLK line from the probe, and the FLASH interpreted that as 2 clocks per edge.

**Comment by DurandA** [comment]
Thank you for your extensive help and sorry for the late reply. Even with your remarks, I wasn't able to enable Quad I/O mode using the ECP5 so I had to fallback to connecting an ESP32 directly to the flash and it worked flawlessly ([snippet here](https://gist.github.com/DurandA/2992dad09b395cfa4491526bf7395ba2)).

> When poking around with new stuff it's easiest to add it here to test: https://github.com/gregdavill/ecpprog/blob/master/ecpprog/ecpprog.c#L955
> That way the SPI bus is already configured, and you can verify the SPI_ID is correct before your custom functions run.

That is exactly how I started. To set the QE bit, I am doing something like that:
```
static void flash_quad_enable()
{
	uint8_t rdsr[2] = { 0x05 };
	xfer_spi(rdsr, 2);
	fprintf(stderr, "SR: 0x%02X\n", rdsr[1]);
	fprintf(stderr, " - WEL: %s\n",
		((rdsr[1] & (1 << 1)) == 0) ? 
			"disabled" : 
			"enabled");	
	fprintf(stderr, " - QE: %s\n",
		((rdsr[1] & (1 << 6)) == 0) ? 
			"disabled" : 
			"enabled");

	uint8_t wrsr[3] = { 0x01, (uint8_t)(1 << 6), 0 };
	send_spi(wrsr, 2); // config register is optional, could also use send_spi(wrsr, 3)

	xfer_spi(rdsr, 2);
	fprintf(stderr, "SR: 0x%02X\n", rdsr[1]);
}
```

And `flash_quad_enable()` is called within the following block:
```
/* Reset ECP5 to release SPI interface */
ecp_jtag_cmd(ISC_ENABLE);
ecp_jtag_cmd(ISC_ERASE);
ecp_jtag_cmd(ISC_DISABLE);

/* Put device into SPI bypass mode */
enter_spi_background_mode();

flash_reset();
flash_write_enable();
flash_quad_enable();
```

However, `send_spi(wrsr, 2)` does not affect the register value. Indeed, _ecpprog_ has to be called without the `--verbose` flag as `flash_write_enable()` sends commands that are not compatible with my flash.

For reference, here is the recommanded flow chart to enable Quad I/O:
![quad-enable-flow](https://user-images.githubusercontent.com/3709037/82452079-175ac380-9aaf-11ea-9420-91579a50f8d3.png)

**Comment by gregdavill** [comment]
Interesting. If you can get a logic analyser on the system it would be interesting to see why it wasn't working over JTAG. But I'm glad you've got it working! :)
