### ISSUE TITLE
Can't find iCE FTDI USB device

### ISSUE THREAD

**Issue by roby2014** [gregdavill/ecpprog#16]
Hey, I've got a Colorlight 5A-75E board (which has a ECP5 FPGA) and a FTDI232. I've managed to connect all the JTAG pins, however, looks like it cant recognize the board:
```
❯ ecpprog -t
init..
Can't find iCE FTDI USB device (vendor_id 0x0403, device_id 0x6010 or 0x6014).
ABORT.
```

Any idea if this a FTDI problem or ? 

`lsusb` shows:
```
Bus 003 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
```

I've also tried to enable permissions on `/dev/ttyUSB0` but no success.

I can provide more info if needed.

**Comment by gregdavill** [comment]
Hi, The FTDI naming can be a bit confusing. This tool only support FT232H, FT2232H, FT4232H parts. The `H` indicates highspeed usb and that the device has the `MPSSE` engine that we use for JTAG. I currently don't have any plans to support the FT232. 

You can try openFPGALoader, which is more featured, and does list some support for the FT232RL.
https://trabucayre.github.io/openFPGALoader/compatibility/cable.html

**Comment by roby2014** [comment]
Oh, right, since the board says only "FTDI232", I thought it was the H model, my bad.
I wonder how hard it would be to implement tho 🤔 
Thanks anyways for answering! Will look at openFPGALoader :)
